### ISSUE TITLE
Recommended ideas to preserve information in the source distorted image after undistorting.

### ISSUE THREAD

**Issue by severecoder** [DiamondLightSource/discorpy#5]
TIA.

The information on the edges of the source image is lost after final unwarping, what is the best solution to maintain that without losing the undistrortion results?

**Comment by nghia-vo** [comment]
You can apply padding to an image, update the center of distortion, then unwarp it as follow:
```python
pad = 200
img_pad = np.pad(img, pad, mode="constant")
img_corrected = post.unwarp_image_backward(img_pad, xcenter + pad, ycenter + pad, 
                                                                             list_bfact, mode="constant")
```
Example of using the image in [demo_8](https://discorpy.readthedocs.io/en/latest/usage/demo_08.html). 
```python
pad = width//2
img_corrected = []
for i in range(img.shape[-1]):
    mat_pad = np.pad(img[:, :, i], pad, mode="constant")
    img_corrected.append(
        post.unwarp_image_backward(mat_pad, xcenter + pad, ycenter + pad,
                                                         list_bfact, mode="constant"))
img_corrected = np.moveaxis(np.asarray(img_corrected), 0, 2)
io.save_image(output_base + "/F_R_hazcam_unwarped_bigger_FOV.png", img_corrected)
```
![F_R_hazcam_unwarped_include_outside](https://user-images.githubusercontent.com/12136997/231868565-4a0e705c-a11f-4463-84e7-d975bb8448d7.jpg)

**Comment by nghia-vo** [comment]
Or another way to keep the corrected image is at the same size as the input:
```python
import scipy.ndimage as ndi

zoom = 2.0
list_bfact1 = zoom * list_bfact
xcenter1 = xcenter * zoom
ycenter1 = ycenter * zoom
img_corrected = []
for i in range(img.shape[-1]):
    img_tmp = ndi.zoom(img[:, :, i], zoom)
    img_tmp = post.unwarp_image_backward(img_tmp, xcenter1, ycenter1, list_bfact1)
    img_corrected.append(ndi.zoom(img_tmp, 1 / zoom))
img_corrected = np.moveaxis(np.asarray(img_corrected), 0, 2)
io.save_image(output_base + "/F_R_hazcam_unwarped_bigger_FOV_same_size.png", img_corrected)
```

**Comment by severecoder** [comment]
Thanks a lot for the quick help. 
I have been trying the padding in the initial input image, along with updating the center based on the updated image size. Is there any recommended rule of thumb for padding here since different images will need different padding size?

**Comment by nghia-vo** [comment]
I've added the answers to documentation: https://discorpy.readthedocs.io/en/latest/usage/tips.html

**Comment by severecoder** [comment]
This does not exactly work exactly as the unwarping parameters are error prone closer to the edge of the images. I fixed the issue by adding extra padding and then crop as post processing. 

Thanks a lot.
