### ISSUE TITLE
[Help wanted] Distortion Correction For a binary grid image

### ISSUE THREAD

**Issue by caolonghao** [DiamondLightSource/discorpy#8]
Hello, dear authors!  I want to do distortion correction for binary image like this 
<img width="457" alt="image" src="https://user-images.githubusercontent.com/57024921/233663838-2e5af0cd-219e-4129-9e8a-a08711de58b6.png">
but it seems not that easy to locate every intersection of the lines, so I decided to use the center of every box to do the correction, like this:
<img width="370" alt="image" src="https://user-images.githubusercontent.com/57024921/233664535-a455e222-709f-4990-a2df-0ea03a69237a.png">
I noticed that discorpy has the function of correcting both radial distortion and perspective distortion. Is there any way to use these points to do the correction? 
Thanks!

**Comment by nghia-vo** [comment]
This demo https://discorpy.readthedocs.io/en/latest/usage/demo_04.html should help you to deal with the line pattern image from the raw data.
However if you have only the binary image and you already get a list points, you can start from the step of grouping points:
```python
list_points_hor_lines = list_points_ver_lines = list_points #  Coordinates of points you found
slope_hor, dist_hor = lprep.calc_slope_distance_hor_lines(mat0)
slope_ver, dist_ver = lprep.calc_slope_distance_ver_lines(mat0)
print("4-> Group points into lines !!!!")
list_hor_lines = prep.group_dots_hor_lines(list_points_hor_lines, slope_hor, dist_hor)
list_ver_lines = prep.group_dots_ver_lines(list_points_ver_lines, slope_ver, dist_ver)
# Optional: remove residual dots
list_hor_lines = prep.remove_residual_dots_hor(list_hor_lines, slope_hor, 2.0)
list_ver_lines = prep.remove_residual_dots_ver(list_ver_lines, slope_ver, 2.0)
io.save_plot_image(output_base + "/grouped_hor_lines.png", list_hor_lines, height, width)
io.save_plot_image(output_base + "/grouped_ver_lines.png", list_ver_lines, height, width)
```
The rest you can copy from that demo. This document: https://discorpy.readthedocs.io/en/latest/tutorials/methods.html explains step-by-step what needs to be done.

**Comment by caolonghao** [comment]
Thanks for your reply, actually the original image looks like this:
<img width="454" alt="image" src="https://user-images.githubusercontent.com/57024921/233755955-08323a01-be67-4556-b97b-a119b088dc24.png">
You can see, at the left corner and right corner, the lines look not that clear, so I'm not sure if regular methods will work. Th
erefore, I use dilate and erode in opencv, then thresholding to make the binary image. 

Actually I tried https://discorpy.readthedocs.io/en/latest/usage/demo_04.html, and it extract points like this: 
![grouped_hor_lines](https://user-images.githubusercontent.com/57024921/233756621-1450e724-bf0d-4540-af90-7cc4526875b5.png)
![grouped_ver_lines](https://user-images.githubusercontent.com/57024921/233756628-64e0a019-8f55-447b-9035-117aa6851bbf.png)

When running the last part of demo4, there occurred an error:
```
!!! ERROR !!!
Parameters of the methods of grouping dots need to be adjusted
ValueError: There're missing lines, algorithm will not work!!!
```

**Comment by nghia-vo** [comment]
The main reason is that it can't locate the center of distortion which is out of the field-of view. Looks like your image is cropped or limited the field of view to show only the top part. Lens distortion of a camera supposed to be symmetric, that is we should see the curve lines change the curve direction going from top to bottom, left to right. In your image I only can see lines bending down, there're no lines bending up. The automated method won't work because it can't locate the center of distortion given only lines bending in one direction: https://discorpy.readthedocs.io/en/latest/tutorials/methods.html#calculating-the-optical-center-of-radial-distortion. 
      A workaround is that you have to guess the distortion coefficients using the routine demonstrated here: https://discorpy.readthedocs.io/en/latest/usage/demo_08.html. You have to change the center of distortion and the coefficients until the overlay lines parallel with the lines in the original image. Or trying to capture a full view of field of the camera if you have access to it.
